#!/usr/bin/env python3
"""
scripts/verify_junit_xml.py

Parses all JUnit XML test report files generated by Gradle/Kotlin Multiplatform test runs
and verifies honest test accounting invariants:
  total == passed + failed + skipped
where:
  failed = failures + errors
  skipped = skipped + disabled

Strict Fail-Closed Invariants:
Exits with code 1 if:
- No JUnit XML report files are found
- Any XML file cannot be parsed
- Any invariant violation is detected (e.g. negative counts or count mismatch)
- Any test failures are found (total_failed > 0)
- Total tests executed across all suites is zero (total_tests == 0)
"""

import glob
import os
import sys
import xml.etree.ElementTree as ET


def verify_junit_xml(search_patterns=None):
    if not search_patterns:
        search_patterns = [
            "**/build/test-results/**/*.xml",
            "build/test-results/**/*.xml"
        ]

    matched_files = []
    for pattern in search_patterns:
        for f in glob.glob(pattern, recursive=True):
            if os.path.isfile(f) and f.endswith(".xml") and f not in matched_files:
                matched_files.append(f)

    if not matched_files:
        print("❌ ERROR: No JUnit XML report files found.", file=sys.stderr)
        print(f"Searched patterns: {search_patterns}", file=sys.stderr)
        sys.exit(1)

    total_suites = 0
    total_tests = 0
    total_passed = 0
    total_failed = 0
    total_skipped = 0
    total_time = 0.0

    print("=" * 90)
    print("JUnit XML Test Results Verification")
    print("=" * 90)
    print(f"{'TEST SUITE':<58} | {'TOTAL':<6} | {'PASS':<6} | {'FAIL':<6} | {'SKIP':<6}")
    print("-" * 90)

    for f in sorted(matched_files):
        try:
            tree = ET.parse(f)
            root = tree.getroot()
            suites = [root] if root.tag == "testsuite" else root.findall(".//testsuite")
            if not suites and root.tag == "testsuites":
                suites = list(root)

            for s in suites:
                name = s.attrib.get("name", os.path.basename(f))
                total = int(s.attrib.get("tests", 0))
                failures = int(s.attrib.get("failures", 0))
                errors = int(s.attrib.get("errors", 0))
                skipped = int(s.attrib.get("skipped", 0)) + int(s.attrib.get("disabled", 0))
                time_str = s.attrib.get("time", "0.0")
                try:
                    time = float(time_str.replace(",", ""))
                except ValueError:
                    time = 0.0

                failed = failures + errors
                passed = total - failed - skipped

                # Honest counting invariant check
                if total != (passed + failed + skipped) or passed < 0 or failed < 0 or skipped < 0:
                    print(
                        f"\n❌ INVARIANT VIOLATION in {f} ({name}): "
                        f"total={total} != passed={passed} + failed={failed} + skipped={skipped}",
                        file=sys.stderr
                    )
                    sys.exit(1)

                total_suites += 1
                total_tests += total
                total_passed += passed
                total_failed += failed
                total_skipped += skipped
                total_time += time

                display_name = name if len(name) <= 58 else "..." + name[-55:]
                print(f"{display_name:<58} | {total:<6} | {passed:<6} | {failed:<6} | {skipped:<6}")

        except ET.ParseError as pe:
            print(f"\n❌ XML PARSE ERROR in {f}: {pe}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"\n❌ ERROR processing {f}: {e}", file=sys.stderr)
            sys.exit(1)

    print("=" * 90)
    print(f"SUMMARY: {total_suites} suites checked across {len(matched_files)} XML files.")
    print(f"TOTAL TESTS : {total_tests}")
    print(f"PASSED      : {total_passed}")
    print(f"FAILED      : {total_failed}")
    print(f"SKIPPED     : {total_skipped}")
    print(f"TOTAL TIME  : {total_time:.2f}s")
    print("=" * 90)

    if total_failed > 0:
        print(f"❌ TEST FAILURES DETECTED: {total_failed} tests failed.", file=sys.stderr)
        sys.exit(1)

    if total_tests == 0:
        print("❌ ERROR: 0 tests were executed across all test suites.", file=sys.stderr)
        sys.exit(1)

    print("✅ All JUnit XML test count invariants (total == passed + failed + skipped) verified.")
    return 0


if __name__ == "__main__":
    patterns = sys.argv[1:] if len(sys.argv) > 1 else None
    sys.exit(verify_junit_xml(patterns))
